#! /bin/bash
alias merge="git merge"
alias add="git add -A"
alias commit="git commit -m"
alias push="git push"
alias pull="git pull"
alias pullf="git pull --ff-only"
alias pushf="git push origin -f"
alias co="git checkout"
alias lg="git lg"
alias diff="git diff"
alias stash="git stash"
alias mergetool="git mergetool"
alias rebase="git rebase"
alias fetch="git fetch"